### ISSUE TITLE
Thank you for your module :)

### ISSUE THREAD

**Issue by ghost** [zeuxisoo/python-pluginplot#1]
I took your code for my minecraft server implementation(incomplete but you can join server). 
Thank you for this great piece of software!
https://github.com/TiberiumPY/puremine
There isn't any issues about license, right?

**Comment by zeuxisoo** [comment]
Thank your for the issue. The license is MIT :)

**Comment by ghost** [comment]
@zeuxisoo OK, I use the same license in my project.

**Comment by ghost** [comment]
@zeuxisoo And question about module - is there a way to reuse Plugin instance in another script in plugin directory( like folder - Example, and inside of it two scripts - plugin.py and anotherscript.py , can anotherscript.py somehow reuse plugin instance from plugin.py ?

**Comment by zeuxisoo** [comment]
Sorry, About this question, You mean is how to reuse plugin at another plugin ?

And the structure like:

```
- app.py
- plugins
   - one
      - script1.py
   - two
      - script2.py
```

The `plugins.one.script1` can using in `plugins.two.script2` ?

**Comment by ghost** [comment]
@zeuxisoo 
`- app.py
- plugins
  - one
    - script1.py
  - two
    - script2.py
    - script3.py`
      I mean that you can, for example, reuse plugin instance from script2.py in script3.py (so they will be like 1 plugin, not two)

**Comment by zeuxisoo** [comment]
Oh, i see ! Your explain is very good :)

Base on the [plugin.py#L116-L127](https://github.com/zeuxisoo/python-pluginplot/blob/master/pluginplot/plugin.py#L116-L127), The answer is no. Because of all plugin folders will register to python module. If you want to merge all scripts to one, you may need to change the register code like using definition file to register plugin and so on.

**Comment by ghost** [comment]
@zeuxisoo I changed a lot, and my code doesn't contain with function. But I got it to work with using global import!

**Comment by ghost** [comment]
@zeuxisoo you can see here - https://github.com/TiberiumPY/puremine/tree/master/plugin_core , that I changed a lot

**Comment by zeuxisoo** [comment]
Thank you for your reference. Your changes is look good and simplifies a lot. But i think it did not meet more situation, like the `examples` usages.

**Comment by ghost** [comment]
@zeuxisoo yes, I know, I just made it for my project, and deleted stuff that I'll not use

**Comment by zeuxisoo** [comment]
Yep, I know, I'm glad you can see the modified version 👍
